### PR TITLE
Force BigInt toJSON instead of using replacer

### PR DESCRIPTION
**Pull request by haoadoresorange**
A custom BigInt.prototype.toJSON can be implemented by users, which will take precedence over the replacer. Meaning the value passed in the replacer is the result of toJSON but NOT the original BigInt.
As a workaround, we force our implementation instead of using replacer.

### CODE REVIEW

**Comment by haoadoresorange** [comment]
Sorry I hit the wrong button that closed it.

**Comment by haoadoresorange** [comment]
When #37 is merged, we might be using a custom `stringify` from `json-bigint`. I looked into the package and apparently it follows the same logic, that is to call `toJSON` if it exists on the data type, hence suffer from the same problem as the current implementation.

That means we will still need to shadow the function at the time of `stringify` to ensure the tsp format. I'll leave the PR here until #37 is merged and then update it accordingly.

**Comment by paul-marechal** [comment]
@haoadoresorange when #37 gets merged there won't be issues serializing `BigInt` values as `json-bigint` ignore `.toJSON` in that case. See the following output from node's repl:

```node-repl
> bigint = require('json-bigint')
[Function] { parse: [Function], stringify: [Function] }
> BigInt.prototype.toJSON = () => 'patate'
[Function]
> bigint.stringify(1n)
'1'
> JSON.stringify(1n)
'"patate"'
```

**Comment by haoadoresorange** [comment]
I agree, this should be closed here.

**Pull request closed without merging**
